apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization


namespace: taskflow


resources:

  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - persistent-volume.yaml
  - persistent-volume-claim.yaml
  - service-account.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - network-policy.yaml
  - pod-disruption-budget.yaml