apiVersion: v1
kind: PersistentVolume

metadata:

  name: taskflow-pv


spec:

  capacity:

    storage: 1Gi


  accessModes:

    - ReadWriteOnce


  hostPath:

    path: /data/taskflow


  persistentVolumeReclaimPolicy: Retain