version: "3.8"

services:

  taskflow:

    container_name: taskflow-app

    build:

      context: ..

      dockerfile: Docker/Dockerfile


    ports:

      - "5000:5000"


    volumes:

      - ../app/data:/app/data


    restart: always